version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: db_patients
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PGDATA}
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./postgres_data/init.sql:/docker-entrypoint-initdb.d/init.sql  

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: web_app
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}