services:
  db:
    image: postgres:latest
    container_name: db_patients
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_patients
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./postgres_data/init.sql:/docker-entrypoint-initdb.d/init.sql  

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: web_app
    ports:
      - 5000:5000
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/db_patients