name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DELL_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 77.242.108.8 >> ~/.ssh/known_hosts

      - name: Deploy to local machine
        run: |
          ssh -i ~/.ssh/id_rsa tatiana@77.242.108.8 "cd /home/tatiana/hospital-appointment &&  git config pull.rebase true && git pull && docker-compose down && docker-compose up --build -d"
